sudo: required
language: python
dist: xenial
python:
  - "3.5"
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
# command to install dependencies
install: pip install -r requirements.txt
# command to run tests
script:
  - python test_swarm.py
notifications:
  slack: fnndsc:gGPIVAOtMikWomA1EKrVYIjO
